on:
  push:
    branches:
    - main
jobs:
  main:
      name: Setup nginx
      uses: cuchi/jinja2-action@v1.3.0
      with:
        template: infra/nginx.conf.j2
        output_file: infra/nginx.conf
        strict: true
        variables: |
          server_host=staging.example.com
          timeout=30s
